### ISSUE TITLE
Display issue on 404 in Light mode

### ISSUE THREAD

**Issue by halans** [horizon-ui/horizon-ai-template-pro#1]
When calling a page that doesn't exist, for example http://localhost:3000/all-templates/blabla
the 404 page is displayed as expected, but in Light mode it's not quite right. In Dark mode it is fine.

Light mode = not OK
![CleanShot 2023-11-25 at 15 33 09@2x](https://github.com/horizon-ui/horizon-ai-template-pro/assets/21991/317f9537-fee8-4248-9701-21964d1e6596)

Dark mode = OK
![CleanShot 2023-11-25 at 15 33 44@2x](https://github.com/horizon-ui/horizon-ai-template-pro/assets/21991/f9f3f440-bd35-4f3e-ab78-784a85ec39bb)

This is on the JS version

**Comment by simmmpleweb** [comment]
I'll come back to this issue as soon as we implement a custom 404 page. Thanks for observing the problem!

**Comment by simmmpleweb** [comment]
We implemented the page! Thanks for your patience! The changes will be up in few minutes when we upload the archive/
Regards, Vlad.
