### ISSUE TITLE
Console React errors

### ISSUE THREAD

**Issue by halans** [horizon-ui/horizon-ai-template-pro#3]
When calling /all-templates the console throws react errors, although React labels them as Warning

![CleanShot 2023-11-25 at 15 44 14@2x](https://github.com/horizon-ui/horizon-ai-template-pro/assets/21991/397d8295-1093-4966-9d0b-2138d4f991f3)

These Warnings also show up in the terminal when calling _npm run dev_.

Is there a way to suppress them? So they don't show up in the console?

**Comment by simmmpleweb** [comment]
Hello, @halans ! I am trying [this](https://github.com/chakra-ui/chakra-ui/issues/5795) out for the first error, as for the second I'm looking into it right now.

**Comment by simmmpleweb** [comment]
They are fixed !
