### ISSUE TITLE
Error thrown when running npm run build

### ISSUE THREAD

**Issue by halans** [horizon-ui/horizon-ai-template-pro#7]
While `npm run dev` runs fine, `npm run build` throws an error:

```
./src/components/menu/ItemContent.jsx
6:33  Error: Parsing error: Unexpected token, expected "," (6:33)
```

As per Copilot "Type annotations can only be used in TypeScript files"

I am using the JS version.
Looks like a TS to JS conversion issue.

`npm run build` is also run when trying to deploy it in the cloud, and is where I noticed it first.

I changed this to 
`export function ItemContent(props) {`
which seems to work fine.

But the `npm run build` still fails on both
```
> Build error occurred
Error: Export encountered errors on following paths:
        /bootstrap-to-tailwind-converter
        /pet-name-generator
```
as per the other two tickets. So they probably also contain TS to JS conversion issues

**Comment by halans** [comment]
So fixed by 

changing TS
`export function ItemContent(props: { info: string }) {`

to JS
`export function ItemContent(props) {`

**Comment by simmmpleweb** [comment]
I fixed all the conversion issues in my last push, the archive should be available soon. Thanks for the feedback ! I will link this in a comment so people don't get confused when i close all other.
Regards, Vlad.
